summary: Listens for approval/rejection messages from Telegram and acts accordingly.
trigger:
  webhook: {}
steps:
  - id: process_telegram_reply
    summary: Process the incoming command from the Telegram webhook.
    script:
      path: ../scripts/telegram_bots/s_telegram_approval_responder.py
      inputs:
        webhook_payload: u/trigger
  - id: check_if_approved
    summary: If the decision was 'approved', publish the content.
    if:
      - condition:
          javascript: return results.process_telegram_reply.decision === 'approved'
        steps:
          - id: publish_to_buffer
            summary: Sending to Buffer for scheduled posting...
            script:
              path: ../scripts/publication/s_post_to_buffer.py
              inputs:
                post_text: u/results.process_telegram_reply.draft.post_text
                media_url: u/results.process_telegram_reply.draft.image_url
      - else:
          - id: log_rejection
            summary: Logging rejected draft for later review.
            script:
              path: ../scripts/meta/s_log_to_google_sheets.py
              inputs:
                log_data: u/results.process_telegram_reply